name: Chromatic
on:
  push:
    branches:
      - "main"
    paths:
      - "packages/ui/**"
      - "!apps/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pnpm
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
